### ISSUE TITLE
zappa cli doesn't work with python3.10

### ISSUE THREAD

**Issue by buko106** [zappa/Zappa#1248]
## Context

Excute zappa command from terminal

```shell
$ zappa <env> status
```

## Expected Behavior

shows current function status

## Actual Behavior

occures following error

```
$ zappa status staging
WARNING:Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/Users/buko106/ghq/github.com/<owner>/<repo>/venv/lib/python3.10/site-packages/botocore/credentials.py", line 531, in _protected_refresh
    metadata = self._refresh_using()

... long stack trace

  File "/Users/buko106/ghq/github.com/<owner>/<repo>/venv/lib/python3.10/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/buko106/ghq/github.com/<owner>/<repo>/venv/lib/python3.10/site-packages/dateutil/parser.py", line 587, in parse
    if (isinstance(tzinfos, collections.Callable) or
AttributeError: module 'collections' has no attribute 'Callable'
Error: No Lambda staging-func detected in us-east-1 - have you deployed yet?

```

## Steps to Reproduce

1. install python 3.10.10
1. Install zappa 0.57.0
1. run `zappa <env> status`

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by monkut** [comment]
Ok, from your traceback this problem seems to be coming from `dateutil`.
Can you post the output of `pip freeze`?

It looks like it's fixed in [2.7.0](https://github.com/dateutil/dateutil/releases/tag/2.7.0).
Can you try to install or upgrade your datetutil version to >=2.7.0?

**Comment by buko106** [comment]
Updating dateutil to latest(2.8.2) resolves this problem.
Thanks for immediate support!
